### ISSUE TITLE
Support go modules

### ISSUE THREAD

**Issue by zerjioang** [miracl/core#58]
As new releases of Go enable by default Go modules, it would be good to migrate current Go library to go mod specification

**Comment by mcarrickscott** [comment]
Yes, good idea. We will look into it.

**Comment by mcarrickscott** [comment]
Implemented - see go/readme.md

**Comment by zerjioang** [comment]
@mcarrickscott doing it that way, just for you to know, modules cannot be resolved dynamically by Go, and hence, manual work is required. that's why go.mod file should exist on repo and it is the best practice to follow. Anyway, due to design of the Go files, I doubt about its consistency since multiple files with different package names are located at same level.
