### ISSUE TITLE
Attack against M-PIN

### ISSUE THREAD

**Issue by mikelodder7** [miracl/core#67]
I believe I have a potential security attack against M-PIN. Since I don't want to post here, where should I post it to discuss?

**Comment by mcarrickscott** [comment]
Hello Michael,

You can discuss with me privately here at ***@***.***

Mike

**Comment by mikelodder7** [comment]
You're email address is redacted.

**Comment by mcarrickscott** [comment]
Sorry, what do you mean?

Mike

**Comment by mcarrickscott** [comment]
Potential attacks always welcome!
