### ISSUE TITLE
modmul may not be working correctly in 32 bit mode

### ISSUE THREAD

**Issue by mikelodder7** [miracl/core#9]
When I run BIG::modmul in 64 bit mode and 32 bit mode I get two completely different answers when using the same inputs. I'm using the BLS12-381 curve. I'm using the Rust language but I don't think it will matter since all the code is the same across any of the languages.

Code
```rust
let a = BIG::fromstring("03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCB".to_string());

let b = BIG::fromstring("0793154FD85631D966EF2470460C78F6A928AE9F5BDBFAC21DF3D753AA278BA751CDFCF95A84188E29D670675E4C9C7C".to_string());

let MODULUS = BIG::fromstring("1A0111EA397FE69A4B1BA7B6434BACD764774B84F38512BF6730D2A0F6B0F6241EABFFFEB153FFFFB9FEFFFFFFFFAAAB".to_string());

let mut x = BIG::modmul(&a, &b, &MODULUS);
println!("x = {}", x.to_hex());
```

In 64-bit mode I get `x=05015FA6469760BFA6D7899FF58062B3CD2BDEDE551B237EA06E49EA2528AEE6F3BF2AB340785206041A56B17E6C317F` 

In 32-bit mode I get 
`x=1782F7D00F6793C274488FF042468F7ACDE8B3971718756AB101076FBDCDDA4CB8EB7225425F243B24D059882A6D2DFC`

Am I doing something wrong here? The only difference is the architecture I'm targeting.

**Comment by mcarrickscott** [comment]
Hello Michael,

The 32-bit result seems to be correct.

I don't recognise the function BIG::fromstring() ? It is not in the library?

Mike

**Comment by mikelodder7** [comment]
The fromstring exists in the apache licensed version [here](https://github.com/miracl/amcl/blob/master/version3/rust/src/big.rs#L340)

However, why is the 32-bit version different than the 64-bit version? Shouldn't those values be the same?

**Comment by mikelodder7** [comment]
Here the actual values if this helps

64-bit
```rust
a =    BIG { w: [241723210806480843,183842942842629240,173352607777404541,169237124882009944,105539184995112064,38834437222783480,828681343] }
b =    BIG { w: [132416828320029820,-36241730206030966,-183175740354038500,-108808289511770161,19716962043635886,150180602526288156,2033276157] }
MODULUS =    BIG { w: [143833713099123371,216172422762594286,83896495553790442,149689799186160835,163057217235613515,171129804685765101,6980443811] }
x =    BIG { w: [7413669724696959,273220737267171713,44651521722183483,250324079510979001,285275312819612638,118738665491260007,1343617636] }
```

32-bit
```rust
a =    BIG { w: [35016651,450244566,379120760,342434165,527808125,322894393,392597336,315228709,528782464,196582050,62347768,72334776,291810431,1] }
b =    BIG { w: [508337276,246645562,17179530,469365429,414872860,195679507,185104335,334199679,380184750,36725703,431737116,279733170,422663421,3] }
MODULUS =    BIG { w: [536849067,267911167,352321518,402652514,258097642,156269400,184392899,278818978,392460107,303717734,315025901,318754100,1121955,13] }
x =    BIG { w: [174927356,109235265,399052489,384060036,497339278,62381798,363512836,316859150,449702067,34747515,487728124,516892548,405765376,11] }
```

**Comment by mcarrickscott** [comment]
It would be better in hex..

But already I think I see a problem. Those negative values in the 64-bit b,
that can't be right. Those numbers should all be positive.

Mike

**Comment by mikelodder7** [comment]
Here's the thing. I've implemented [hash to curve](https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/?include_text=1) and the 64 bit version works and matches test vectors but the 32-bit does not

**Comment by mikelodder7** [comment]
Right now the values in `w` are i64. If unsigned is desired, it should be u64

**Comment by mikelodder7** [comment]
Those values happen when I'm doing map_to_curve

**Comment by mcarrickscott** [comment]
Hello Michael,

Basically I am unable to reproduce your problem.

This is what I did.. I inserted this code

let mut a =
big::BIG::fromstring("03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCB".to_string());
let mut b =
big::BIG::fromstring("0793154FD85631D966EF2470460C78F6A928AE9F5BDBFAC21DF3D753AA278BA751CDFCF95A84188E29D670675E4C9C7C".to_string());
let mut MODULUS =
big::BIG::fromstring("1A0111EA397FE69A4B1BA7B6434BACD764774B84F38512BF6730D2A0F6B0F6241EABFFFEB153FFFFB9FEFFFFFFFFAAAB".to_string());
let mut x = big::BIG::modmul(&a, &b, &MODULUS);

println!("a = {}", a.tostring());
println!("b = {}", b.tostring());
println!("m = {}", MODULUS.tostring());
println!("x = {}", x.tostring());

 into BenchtestALL.rs at the start of this function

fn bls12383(mut rng: &mut RAND) {

Then I renamed bls12383 to bls12381 throughout. I built the library in
64-bit mode from curves 1,3,7,25,28,33,34,36

Then I build BenchtestALL and ran it, and got this output

a =
03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCB
b =
0793154FD85631D966EF2470460C78F6A928AE9F5BDBFAC21DF3D753AA278BA751CDFCF95A84188E29D670675E4C9C7C
m =
1A0111EA397FE69A4B1BA7B6434BACD764774B84F38512BF6730D2A0F6B0F6241EABFFFEB153FFFFB9FEFFFFFFFFAAAB
x =
1782F7D00F6793C274488FF042468F7ACDE8B3971718756AB101076FBDCDDA4CB8EB7225425F243B24D059882A6D2DFC

which is as expected.

I expect to release a version of the core library later this week which
runs (and matches) most of the hash-to-curve test vectors.

Mike

**Comment by mikelodder7** [comment]
So I expect x to be `05015FA6469760BFA6D7899FF58062B3CD2BDEDE551B237EA06E49EA2528AEE6F3BF2AB340785206041A56B17E6C317F` and I'm getting `1782F7D00F6793C274488FF042468F7ACDE8B3971718756AB101076FBDCDDA4CB8EB7225425F243B24D059882A6D2DFC` 

The version that works with hash to curve is expected to be `1782F7D00F6793C274488FF042468F7ACDE8B3971718756AB101076FBDCDDA4CB8EB7225425F243B24D059882A6D2DFC`

**Comment by mikelodder7** [comment]
If you want I'm happy to connect over zoom or other synchronous video like slack.

**Comment by mikelodder7** [comment]
The project where this happens is [hash2curve](https://github.com/mikelodder7/hash2curve)

if you run `cargo test` in 64-bit mode it works and 32-bit mode it fails

**Comment by mcarrickscott** [comment]
I am confused. 178...DFC is the correct result. It is the result I get in
both 32 and 64 bit builds.

Why would you expect 05015..17F?

Mike

**Comment by mikelodder7** [comment]
Try this.
`git clone https://github.com/mikelodder7/hash2curve.git`
`cd hash2curve`

Now in a 64-bit environment run: 

`cargo test map_to_curve_nu_tests --features=bls -- --nocapture`
The output will look like this:

```
line 323: tv1 = 108264BE7AE732CC00F0B64249E2C74769EFB82280226D1E2B18BB8A7243B848AA0B94B1C6C5EF5324D14FFAFA0B7555
line 326: tv2 = 0489F08CAF89E82D1FFF5977D9A4ED09F7092E2D3ED2A0C1555AF97FDCDA71E3D47C685786D4B68AF2EFFA5F09456566
line 332:  x1 = 150C554B2A711AF920F00FBA2387B45160F8E64FBEF50DDF8073B50A4F1E2A2C7E87FD094D9AA5DE17C14A5A0350DABB
line 336:  x1 = 03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCA
line 340:  e1 = 0
line 344:  x1 = 03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCB
line 348:  x1 = 03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCB
a =    BIG { w: [241723210806480843,183842942842629240,173352607777404541,169237124882009944,105539184995112064,38834437222783480,828681343] }
b =    BIG { w: [132416828320029820,-36241730206030966,-183175740354038500,-108808289511770161,19716962043635886,150180602526288156,2033276157] }
MODULUS =    BIG { w: [143833713099123371,216172422762594286,83896495553790442,149689799186160835,163057217235613515,171129804685765101,6980443811] }
line 352:  x1 = 05015FA6469760BFA6D7899FF58062B3CD2BDEDE551B237EA06E49EA2528AEE6F3BF2AB340785206041A56B17E6C317F
x =    BIG { w: [7413669724696959,273220737267171713,44651521722183483,250324079510979001,285275312819612638,118738665491260007,1343617636] }
line 359: gx1 = 04E0D041C50C7FB6DA5DE411C1C681599237BFAEC3A04EAA41073BAAB36F0672550286788C9903D0F4D43E12039EF593
line 363: gx1 = 161C553F03D0FD62D0B618EE1ED944DC78AB0AF40A703A3043B3F0DD14255235C7B6D5BFB1CD101A225C7F1465FBCCD6
line 368: gx1 = 0EFDD3E1DBB996F88725842050CC8640344A8160093A67E17D3CDF8BEC67BB07032DF71B31E5FAC03A29C7FDF4134E0B
line 372:  x2 = 0EBFD600DEAE2A5F1A533029D3B7D29FBB9F772451894B923FAB945AE5DAB8BE4D4DB024893885BB83C03CF916F83EDE
line 376: tv2 = 11470FFD4231DEB899A37696E6618BFE839BDA4CB4E0F25D0F494DCC788D245829C9D79123C016DD127796483C0A41A7
line 380: gx2 = 021A61F93E57551280425D7EE56C6D6515BFF8803BD72685F383DD16F32743A8419219A06159937DD52BFE4CC767E00A
line 424:pdiv2= 0D0088F51CBFF34D258DD3DB21A5D66BB23BA5C279C2895FB39869507B587B120F55FFFF58A9FFFFDCFF7FFFFFFFD555
line 384:  e2 = 1
line 389:   x = 05015FA6469760BFA6D7899FF58062B3CD2BDEDE551B237EA06E49EA2528AEE6F3BF2AB340785206041A56B17E6C317F
line 394:  y2 = 0EFDD3E1DBB996F88725842050CC8640344A8160093A67E17D3CDF8BEC67BB07032DF71B31E5FAC03A29C7FDF4134E0B
line 398:   y = 02E7FE461125F230C4C556790358006E5755136CB1787CFA8BC4826591C805267554AC6D46837EA9EECDCE2764C89A05
line 402:  e3 = 1
line 406:y_neg= 171913A42859F4698656513D3FF3AC690D223818420C95C4DB6C503B64E8F0FDA95753916AD08155CF3131D89B3710A6
line 408:y_neg= 02E7FE461125F230C4C556790358006E5755136CB1787CFA8BC4826591C805267554AC6D46837EA9EECDCE2764C89A05
           C1 = 0793154FD85631D966EF2470460C78F6A928AE9F5BDBFAC21DF3D753AA278BA751CDFCF95A84188E29D670675E4C9C7C
           C2 = 025D302C90DD14F6C102839C34A9C9E509221E235BF4D328AC4A41B18ACA44EC02C9D1743EAA8BA2E25CFFFFFFFFF83E
      MODULUS = 1A0111EA397FE69A4B1BA7B6434BACD764774B84F38512BF6730D2A0F6B0F6241EABFFFEB153FFFFB9FEFFFFFFFFAAAB
```

Look where it says line 352.

Now run it in a 32-bit environment

```
line 323: tv1 = 108264BE7AE732CC00F0B64249E2C74769EFB82280226D1E2B18BB8A7243B848AA0B94B1C6C5EF5324D14FFAFA0B7555
line 326: tv2 = 0489F08CAF89E82D1FFF5977D9A4ED09F7092E2D3ED2A0C1555AF97FDCDA71E3D47C685786D4B68AF2EFFA5F09456566
line 332:  x1 = 150C554B2A711AF920F00FBA2387B45160F8E64FBEF50DDF8073B50A4F1E2A2C7E87FD094D9AA5DE17C14A5A0350DABB
line 336:  x1 = 03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCA
line 340:  e1 = 0
line 344:  x1 = 03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCB
line 348:  x1 = 03164AC7F227DEDC0EDD67E176F3545F8494809650112DD9A3D6267DF473F75B67DA3490BADA63B1E35AC5FAC2164FCB
a =    BIG { w: [35016651,450244566,379120760,342434165,527808125,322894393,392597336,315228709,528782464,196582050,62347768,72334776,291810431,1] }
b =    BIG { w: [508337276,246645562,17179530,469365429,414872860,195679507,185104335,334199679,380184750,36725703,431737116,279733170,422663421,3] }
MODULUS =    BIG { w: [536849067,267911167,352321518,402652514,258097642,156269400,184392899,278818978,392460107,303717734,315025901,318754100,1121955,13] }
line 352:  x1 = 1782F7D00F6793C274488FF042468F7ACDE8B3971718756AB101076FBDCDDA4CB8EB7225425F243B24D059882A6D2DFC
x =    BIG { w: [174927356,109235265,399052489,384060036,497339278,62381798,363512836,316859150,449702067,34747515,487728124,516892548,405765376,11] }
line 359: gx1 = 00F2218A335BC86AC2FA23CAA687B3273C6141762F2C4287B09CCE63489F763B925CDDA1856C0B83497C675322D67EFD
line 363: gx1 = 1949EFAE8596097290C6F28DEADD905E3BA23ACC36156466E87196078110F3D67FFC40449FBD8E357FDC5008B8628BAE
line 368: gx1 = 122B6E515D7EA30847365DC01CD0D1C1F741B13834DF921821FA84B659535CA7BB7361A01FD678DB97A998F2467A0CE3
line 372:  x2 = 11AB54C885807E938C20ED8102C08656852377934C7988EB27A12A512997A231B0F40715BB42A5DBCEA4CFD970399FFA
line 376: tv2 = 11470FFD4231DEB899A37696E6618BFE839BDA4CB4E0F25D0F494DCC788D245829C9D79123C016DD127796483C0A41A7
line 380: gx2 = 0850B665C93673B755A71DF7D42FE1146D797CC01B747CAC8B8B9EB5AFDB64D9926FA95E24DAE9DCC63C37F14AE4D3EE
line 424:pdiv2= 0D0088F51CBFF34D258DD3DB21A5D66BB23BA5C279C2895FB39869507B587B120F55FFFF58A9FFFFDCFF7FFFFFFFD555
line 384:  e2 = 1
line 389:   x = 1782F7D00F6793C274488FF042468F7ACDE8B3971718756AB101076FBDCDDA4CB8EB7225425F243B24D059882A6D2DFC
line 394:  y2 = 122B6E515D7EA30847365DC01CD0D1C1F741B13834DF921821FA84B659535CA7BB7361A01FD678DB97A998F2467A0CE3
line 398:   y = 12F0A9D97CDA2E8663E1CBE89708F7C9028A0DC41374C7AE9630C020556917A1E2C03D96B027F0620F0BE4860002A96A
line 402:  e3 = 0
line 406:y_neg= 0F106810CCA5B814E739DBCDAC42B50E61ED3EC0E0105B10D1001280A14FDE823BEBC268012C0F9DAEF31B79FFFD0141
line 408:y_neg= 0F106810CCA5B814E739DBCDAC42B50E61ED3EC0E0105B10D1001280A14FDE823BEBC268012C0F9DAEF31B79FFFD0141
           C1 = 0793154FD85631D966EF2470460C78F6A928AE9F5BDBFAC21DF3D753AA278BA751CDFCF95A84188E29D670675E4C9C7C
           C2 = 025D302C90DD14F6C102839C34A9C9E509221E235BF4D328AC4A41B18ACA44EC02C9D1743EAA8BA2E25CFFFFFFFFF83E
      MODULUS = 1A0111EA397FE69A4B1BA7B6434BACD764774B84F38512BF6730D2A0F6B0F6241EABFFFEB153FFFFB9FEFFFFFFFFAAAB
```

Look where it says line 352.

In 64-bit mode, it will pass all the test vectors from hash 2 curve and fail in 32-bit mode

**Comment by mcarrickscott** [comment]
I see what the problem is.

Big numbers in AMCL and Core are represented as digits to a base somewhat
less than the full word size. So on a 32-bit computer typically only 29
bits are used, on a 64-bit computer only typically 56 bits. So negative
digits should never happen. I note that in your constants folder for
example C1 has negative digits. This represents an overflow of the valid
representation.

Now it is possible to add and subtract such numbers digit by digit,
resulting in a temporary non-fatal overflow. But eventually such numbers
must be normalised back to the valid representation. For example look at
this typical piece of code

                var y3=FP(t0)
                y3.add(t2); y3.norm()
                z.mul(t1)
                t1.copy(t2); t1.add(t2); t2.add(t1)
                t0.sub(t2); t0.norm(); y3.mul(t0); y3.add(x3)
                t1.copy(x); t1.mul(y)
                x.copy(t0); x.norm(); x.mul(t1); x.add(x)
                x.norm()
                y.copy(y3); y.norm()

Observe that after a couple of additions at most, the Big number is
normalised by a call to norm(). The quick fix is to call norm() after every
addition or subtraction or negation. They are not needed after
multiplication, but the inputs to multiplications and squarings must be
normalised.

The idea is that addition and subtraction are very fast. And it is valid to
add at least twice before normalising. Observe that two 29-bit numbers can
be added to give a 30-bit result. That is OK. Two 30-bit numbers can be
added to give a 31-bit result. Still OK, but now the number must be
normalised before it is used again, as two 31-bit numbers if added  gives a
32-bit result which may be negative and hence invalid due to numeric
overflow. And two 32 bit numbers if added is a clear-cut overflow.

Note that the 32-bit representation is more vulnerable in this regard, as
it has less "head-room". The internal code is written assuming just two
bits of head-room. You can detect where overflow occurs by uncommenting the
DEBUG_NORM flag in the C or CPP versions of the code.


Mike

**Comment by mikelodder7** [comment]
Hmmm, I tried adding a `x1.norm()` after BIG::modmul and that didn't fix it. I've tried add .norm() after every call and that didn't fix it either. Is there something else I can try

**Comment by mcarrickscott** [comment]
How did those negative digits get into the constant c1? They should not be
there. In the 32 bit version every digit MUST be Positive and less than 2^29


Mike

**Comment by mikelodder7** [comment]
In the 32 bit version there are no negative numbers

**Comment by mikelodder7** [comment]
Calling norm doesn’t affect any of the numbers in either mode

**Comment by mcarrickscott** [comment]
But there are in the 64bit code and they shouldn’t be. This indicates to me
that the constant is malformed. And if it’s malformed in the 64 bit code
then it’s probably wrong in the 32bit code as well. It’s not enough not to
be negative, each limb must be less than 2^29

Mike

**Comment by mikelodder7** [comment]
What’s throwing me off is that it’s passing the hash to curve tests in spite of that. “These are not the droids you’re looking for”

**Comment by mikelodder7** [comment]
I’ve called norm on the 64 bit to eliminate the negative numbers but it doesn’t affect the overall result

**Comment by mikelodder7** [comment]
I’ve put norm everywhere in the code. Still passes the tests in 64 bit lose but fails in 32 bit lode

**Comment by mcarrickscott** [comment]
No, that’s not enough. It’s too late at that stage, the damage may already
have been done.

Send me you code for generating c1 I will have a look at it tomorrow.

Mike

**Comment by mcarrickscott** [comment]
Hello Michael,

As suspected, the values of c1 are different for 32-bit and 64-bit versions

c1 (32-bit) = 793154FD85631D966EF2470460C78F6A928A*E*9F5BDBFAC21DF3*D*
753AA278BA751*C*DFCF95A84188E29D670675E4C9C7C
c1 (64-bit) = 793154FD85631D966EF2470460C78F6A928A*D*9F5BDBFAC21DF3*9*
753AA278BA751*B*DFCF95A84188E29D670675E4C9C7C

At first glance they look the same, but they are not. The 32-bit value is
wrong - during the calculation that created it suffered overflow.

Mystery solved!

Mike
